#!/bin/bash
# Operates the DB on table customers, for list, add, modify and delete customer
# It uses the local static variables of the worker.py script as NETO_HOME_DIRECTORY and DB_PATH_NAME, unless
# a full path name to a TinyDB database is specified.
# example:
#        ../tinydb/scripts/worker.py -l customers /full/path/name/database.json
#
echo "DB Customers ************"
echo "  1) list customers"
echo "  2) add customer"
echo "  3) modify customer"
echo "  4) delete customer"
echo
read -r -n 1 -p "Select option: " opc
echo
echo
case $opc in
  1) python3 ""$HOME""/neto/tinydb/scripts/worker.py -l customers
	  ;;
  2) python3 ""$HOME""/neto/tinydb/scripts/worker.py -a customers
    ;;
  3) python3 ""$HOME""/neto/tinydb/scripts/worker.py -m customers
    ;;
  4) python3 ""$HOME""/neto/tinydb/scripts/worker.py -d customers
    ;;

  *) echo "invalid option";;
esac
